Comparing and Arrays
EPAM-Online-Courses/helpers pull request #7
Opened 2021-01-26 05:32 UTC by LukaszProkop

Demonstration of given task "Comparing and Arrays". This project shows how to use Arrays.compare() with primitive and object type arrays.

2021-01-26 05:38 UTC, LukaszProkop commented
Task ready for review (I have EOF line, but it's not present on github).

2021-01-26 09:36 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/comparingArrays/ArraysCompare.java
> +package com.epam.prejap.ess.helpers.comparingArrays;
Packages names by conventions rather avoid mixed case. You can just join two words in the big one, all small case.

2021-01-26 09:37 UTC, marcin-ogorzalek-EPAM commented on pom.xml
> +        <maven.compiler.target>${project.java.version}</maven.compiler.target>
Why that two lines when there is `<maven.compiler.release>${project.java.version}</maven.compiler.release>`

2021-01-26 12:25 UTC, LukaszProkop commented on pom.xml
> +        <maven.compiler.target>${project.java.version}</maven.compiler.target>
Deleted

2021-01-26 12:30 UTC, LukaszProkop commented
@marcin-ogorzalek-EPAM Corrected

2021-01-27 08:15 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/comparingarrays/ArraysCompare.java
> +        int[] second = {0, 1, 1, 9, 5, 4};
You shouldn't divide an example code with the documentation. First put a commentary and whole code. In other cse it can be a bit missleading and harder to follow.

2021-01-27 08:22 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/comparingarrays/ArraysCompare.java
> +        second = new int[]{0, 1, 1, 9, 5, 4, 0, 1, 1, 9, 5, 4, 0, 1, 1, 9, 5, 4, 0, 1, 1, 9, 5, 4,};
Remember that creating new variables is not as costly as it used to be. IMO you should declare the new pair instead of reusing the old one. I would say that `third` and `fourth` ok.

2021-01-27 08:22 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/comparingarrays/ArraysCompare.java
> +        Comparing first with second Object type array lexicographically using a specified comparator,
You rather mean hear object of the `Train` class not `Object`.

2021-01-27 08:24 UTC, marcin-ogorzalek-EPAM requested changes

2021-01-27 08:24 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/comparingarrays/ArraysCompare.java
> +        Comparing first with second Object type array lexicographically using a specified comparator,
or so called "a given type".

2021-01-27 08:25 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/comparingarrays/ArraysCompare.java
> +                Arrays.compare(firstObj, 2, 5, secondObj, 2, 5, new TrainById()));
What with version fo the `Arrays.compare` with `Comparator`?

2021-01-27 08:30 UTC, LukaszProkop commented on src/main/java/com/epam/prejap/ess/helpers/comparingarrays/ArraysCompare.java
> +        Comparing first with second Object type array lexicographically using a specified comparator,
@marcin-ogorzalek-EPAM Can i call it non-primitive type?

2021-01-27 09:51 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/comparingarrays/ArraysCompare.java
> +        Comparing first with second Object type array lexicographically using a specified comparator,
Yeah why not

2021-01-27 09:51 UTC, marcin-ogorzalek-EPAM commented
Remember to fix a merge confilt and bump up the varsion.

2021-01-28 11:00 UTC, LukaszProkop commented
@marcin-ogorzalek-EPAM Corrected and added tests to verify exceptions

2021-01-28 12:12 UTC, marcin-ogorzalek-EPAM requested changes
Please add your test to `testng.xml` file that was added to the project.

2021-01-28 15:45 UTC, LukaszProkop commented
Added tests to testng.xml

2021-01-28 20:46 UTC, LukaszProkop commented
@marcin-ogorzalek-EPAM Merged and ready for review

2021-01-28 22:36 UTC, TJB4epam commented
Lecture code was added with small POM changes, please pull and update.

2021-01-29 00:08 UTC, LukaszProkop commented
@marcin-ogorzalek-EPAM @TJB4epam Merged and updated

2021-01-29 12:05 UTC, marcin-ogorzalek-EPAM approved these changes

2021-01-29 12:05 UTC, merged