#7 - Solution for Collections.emptyList vs Collections.EMPTY_LIST
EPAM-Online-Courses/helpers pull request #8
Opened 2021-07-04 21:05 UTC by michal-majewski

I have prepared some code with a brief description about obtaining an empty list from the Collection class. Let me know if it is an acceptable way to introduce this topic.

2021-07-08 10:39 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +            System.out.println(msgForUnsuccessfulModification);
Why not `System.err.println`?

2021-07-08 10:42 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +    }
This should be closer to `private final List EMPTY_LIST = Collections.EMPTY_LIST;`. in that way someone will be able to compare those two quickly.

2021-07-08 10:43 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +        System.out.println(Collections.EMPTY_LIST instanceof List ? "The Collections.EMPTY_LIST is an instance of List" : "The Collections.EMPTY_LIST is NOT an instance of LIst");
```suggestion
        System.out.println(Collections.EMPTY_LIST instanceof List ? "The Collections.EMPTY_LIST is an instance of List" : "The Collections.EMPTY_LIST is NOT an instance of List");
```

2021-07-08 10:44 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +        System.out.println(Collections.EMPTY_LIST instanceof List ? "The Collections.EMPTY_LIST is an instance of List" : "The Collections.EMPTY_LIST is NOT an instance of LIst");
BTW why this is not enclosed in some method as with previous calls.

2021-07-08 10:45 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +        System.out.println(Collections.EMPTY_LIST instanceof List ? "The Collections.EMPTY_LIST is an instance of List" : "The Collections.EMPTY_LIST is NOT an instance of LIst");
And where is javadoc?

2021-07-08 10:46 UTC, marcin-ogorzalek-EPAM requested changes
Some changes and answers requested.

2021-07-12 20:20 UTC, michal-majewski commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +            System.out.println(msgForUnsuccessfulModification);
Amendments done

2021-07-12 20:23 UTC, michal-majewski commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +    }
Good point. Changes done

2021-07-13 21:18 UTC, michal-majewski commented
Changes done after your remarks. I'm asking for another review.

2021-07-14 10:07 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +         * */
```suggestion
         */
```

2021-07-14 10:08 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +         * */
```suggestion
         */
```

2021-07-14 10:09 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +         * */
```suggestion
         */
```

I can see that in many places to be fixed. To end multiline comment you can just use `*/` without additional asterisk.

2021-07-14 10:10 UTC, marcin-ogorzalek-EPAM commented on src/main/java/com/epam/prejap/ess/helpers/collections/EmptyListComparison.java
> +        System.out.println(checkIfProvidedEmptyListIsAnInstanceOfRawList(Collections.EMPTY_LIST)
I would gladly see some comment here similar to one from lines 101-103.

2021-07-14 10:11 UTC, marcin-ogorzalek-EPAM requested changes
One additional comment required and some cosmetic changes (remember about those not pointed out directly.

Generally good job. Can be merged after fixes.

2021-07-14 21:48 UTC, michal-majewski commented
Changes done. Third time lucky, perhaps? :)

2021-07-15 05:37 UTC, marcin-ogorzalek-EPAM approved these changes

2021-07-15 05:38 UTC, merged

2021-07-15 05:39 UTC, marcin-ogorzalek-EPAM commented
Indeed, the third time's the charm.